env:
  LOCATION: "northeurope"
  LOCATION_NAME: "northeu"

on: [push]
name: Azure ARM

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        region: $LOCATION
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        template: ./azure_infra/main.bicep
        parameters: "location=$LOCATION locationName=$LOCATION_NAME"
        # resourceGroupName: ${{ secrets.AZURE_RG }}
        # failOnStdErr: false
